/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");

  /**
  * @constructor
  * @memberof order
  */
  OrderTaxRate = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof order.OrderTaxRate
    * @private
    */
    initialize: function() {
      this._class_ = OrderTaxRate;
      this.id = undefined;
      this.name = undefined;
      this.amount = undefined;
    },

    /**
    * Set the field value
    * @memberof order.OrderTaxRate
    * @param {String} id 
    */
    setId: function(id) {
      this.id = id;
    },

    /**
    * Get the field value
    * @memberof order.OrderTaxRate
    * @return {String} 
    */
    getId: function() {
      return this.id;
    },

    /**
    * Set the field value
    * @memberof order.OrderTaxRate
    * @param {String} name 
    */
    setName: function(name) {
      this.name = name;
    },

    /**
    * Get the field value
    * @memberof order.OrderTaxRate
    * @return {String} 
    */
    getName: function() {
      return this.name;
    },

    /**
    * Set the field value
    * @memberof order.OrderTaxRate
    * @param {Number} amount must be a long integer
    */
    setAmount: function(amount) {
      this.amount = amount;
    },

    /**
    * Get the field value
    * @memberof order.OrderTaxRate
    * @return {Number} must be a long integer
    */
    getAmount: function() {
      return this.amount;
    },

    /**
    * @memberof order.OrderTaxRate
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

OrderTaxRate._meta_ =  {fields:  {}};
OrderTaxRate._meta_.fields["id"] = {};
OrderTaxRate._meta_.fields["id"].type = String;
OrderTaxRate._meta_.fields["name"] = {};
OrderTaxRate._meta_.fields["name"].type = String;
OrderTaxRate._meta_.fields["amount"] = {};
OrderTaxRate._meta_.fields["amount"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = OrderTaxRate;
}

