/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var payments_BatchCardTotal = require("../payments/BatchCardTotal");
var payments_BatchTotalStats = require("../payments/BatchTotalStats");
var payments_ServerTotalStats = require("../payments/ServerTotalStats");

  /**
  * @constructor
  * @memberof payments
  */
  BatchDetail = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof payments.BatchDetail
    * @private
    */
    initialize: function() {
      this._class_ = BatchDetail;
      this.batchTotals = undefined;
      this.serverTotals = undefined;
      this.cardTotals = undefined;
      this.openTips = undefined;
      this.openTabs = undefined;
    },

    /**
    * Set the field value
    * @memberof payments.BatchDetail
    * @param {payments.BatchTotalStats} batchTotals 
    */
    setBatchTotals: function(batchTotals) {
      this.batchTotals = batchTotals;
    },

    /**
    * Get the field value
    * @memberof payments.BatchDetail
    * @return {payments.BatchTotalStats} 
    */
    getBatchTotals: function() {
      return this.batchTotals;
    },

    /**
    * Set the field value
    * @memberof payments.BatchDetail
    * @param {Array.<payments.ServerTotalStats>} serverTotals An array of 
    */
    setServerTotals: function(serverTotals) {
      this.serverTotals = serverTotals;
    },

    /**
    * Get the field value
    * @memberof payments.BatchDetail
    * @return {Array.<payments.ServerTotalStats>} An array of 
    */
    getServerTotals: function() {
      return this.serverTotals;
    },

    /**
    * Set the field value
    * @memberof payments.BatchDetail
    * @param {Array.<payments.BatchCardTotal>} cardTotals An array of 
    */
    setCardTotals: function(cardTotals) {
      this.cardTotals = cardTotals;
    },

    /**
    * Get the field value
    * @memberof payments.BatchDetail
    * @return {Array.<payments.BatchCardTotal>} An array of 
    */
    getCardTotals: function() {
      return this.cardTotals;
    },

    /**
    * Set the field value
    * Number of open tips.
    *
    * @memberof payments.BatchDetail
    * @param {Number} openTips must be a long integer
    */
    setOpenTips: function(openTips) {
      this.openTips = openTips;
    },

    /**
    * Get the field value
    * Number of open tips.
    * @memberof payments.BatchDetail
    * @return {Number} must be a long integer
    */
    getOpenTips: function() {
      return this.openTips;
    },

    /**
    * Set the field value
    * Number of open tabs.
    *
    * @memberof payments.BatchDetail
    * @param {Number} openTabs must be a long integer
    */
    setOpenTabs: function(openTabs) {
      this.openTabs = openTabs;
    },

    /**
    * Get the field value
    * Number of open tabs.
    * @memberof payments.BatchDetail
    * @return {Number} must be a long integer
    */
    getOpenTabs: function() {
      return this.openTabs;
    },

    /**
    * @memberof payments.BatchDetail
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

BatchDetail._meta_ =  {fields:  {}};
BatchDetail._meta_.fields["batchTotals"] = {};
BatchDetail._meta_.fields["batchTotals"].type = payments_BatchTotalStats;
BatchDetail._meta_.fields["serverTotals"] = {};
BatchDetail._meta_.fields["serverTotals"].type = Array;
BatchDetail._meta_.fields["serverTotals"].elementType = payments_ServerTotalStats;
BatchDetail._meta_.fields["cardTotals"] = {};
BatchDetail._meta_.fields["cardTotals"].type = Array;
BatchDetail._meta_.fields["cardTotals"].elementType = payments_BatchCardTotal;
BatchDetail._meta_.fields["openTips"] = {};
BatchDetail._meta_.fields["openTips"].type = Number;
BatchDetail._meta_.fields["openTabs"] = {};
BatchDetail._meta_.fields["openTabs"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = BatchDetail;
}

