/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var payments_BatchTotalType = require("../payments/BatchTotalType");

  /**
  * @constructor
  * @memberof payments
  */
  BatchTotalStats = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof payments.BatchTotalStats
    * @private
    */
    initialize: function() {
      this._class_ = BatchTotalStats;
      this.sales = undefined;
      this.refunds = undefined;
      this.net = undefined;
      this.giftCardLoads = undefined;
      this.giftCardCashOuts = undefined;
      this.tax = undefined;
      this.tips = undefined;
    },

    /**
    * Set the field value
    * @memberof payments.BatchTotalStats
    * @param {payments.BatchTotalType} sales 
    */
    setSales: function(sales) {
      this.sales = sales;
    },

    /**
    * Get the field value
    * @memberof payments.BatchTotalStats
    * @return {payments.BatchTotalType} 
    */
    getSales: function() {
      return this.sales;
    },

    /**
    * Set the field value
    * @memberof payments.BatchTotalStats
    * @param {payments.BatchTotalType} refunds 
    */
    setRefunds: function(refunds) {
      this.refunds = refunds;
    },

    /**
    * Get the field value
    * @memberof payments.BatchTotalStats
    * @return {payments.BatchTotalType} 
    */
    getRefunds: function() {
      return this.refunds;
    },

    /**
    * Set the field value
    * @memberof payments.BatchTotalStats
    * @param {payments.BatchTotalType} net 
    */
    setNet: function(net) {
      this.net = net;
    },

    /**
    * Get the field value
    * @memberof payments.BatchTotalStats
    * @return {payments.BatchTotalType} 
    */
    getNet: function() {
      return this.net;
    },

    /**
    * Set the field value
    * @memberof payments.BatchTotalStats
    * @param {payments.BatchTotalType} giftCardLoads 
    */
    setGiftCardLoads: function(giftCardLoads) {
      this.giftCardLoads = giftCardLoads;
    },

    /**
    * Get the field value
    * @memberof payments.BatchTotalStats
    * @return {payments.BatchTotalType} 
    */
    getGiftCardLoads: function() {
      return this.giftCardLoads;
    },

    /**
    * Set the field value
    * @memberof payments.BatchTotalStats
    * @param {payments.BatchTotalType} giftCardCashOuts 
    */
    setGiftCardCashOuts: function(giftCardCashOuts) {
      this.giftCardCashOuts = giftCardCashOuts;
    },

    /**
    * Get the field value
    * @memberof payments.BatchTotalStats
    * @return {payments.BatchTotalType} 
    */
    getGiftCardCashOuts: function() {
      return this.giftCardCashOuts;
    },

    /**
    * Set the field value
    * @memberof payments.BatchTotalStats
    * @param {payments.BatchTotalType} tax 
    */
    setTax: function(tax) {
      this.tax = tax;
    },

    /**
    * Get the field value
    * @memberof payments.BatchTotalStats
    * @return {payments.BatchTotalType} 
    */
    getTax: function() {
      return this.tax;
    },

    /**
    * Set the field value
    * @memberof payments.BatchTotalStats
    * @param {payments.BatchTotalType} tips 
    */
    setTips: function(tips) {
      this.tips = tips;
    },

    /**
    * Get the field value
    * @memberof payments.BatchTotalStats
    * @return {payments.BatchTotalType} 
    */
    getTips: function() {
      return this.tips;
    },

    /**
    * @memberof payments.BatchTotalStats
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

BatchTotalStats._meta_ =  {fields:  {}};
BatchTotalStats._meta_.fields["sales"] = {};
BatchTotalStats._meta_.fields["sales"].type = payments_BatchTotalType;
BatchTotalStats._meta_.fields["refunds"] = {};
BatchTotalStats._meta_.fields["refunds"].type = payments_BatchTotalType;
BatchTotalStats._meta_.fields["net"] = {};
BatchTotalStats._meta_.fields["net"].type = payments_BatchTotalType;
BatchTotalStats._meta_.fields["giftCardLoads"] = {};
BatchTotalStats._meta_.fields["giftCardLoads"].type = payments_BatchTotalType;
BatchTotalStats._meta_.fields["giftCardCashOuts"] = {};
BatchTotalStats._meta_.fields["giftCardCashOuts"].type = payments_BatchTotalType;
BatchTotalStats._meta_.fields["tax"] = {};
BatchTotalStats._meta_.fields["tax"].type = payments_BatchTotalType;
BatchTotalStats._meta_.fields["tips"] = {};
BatchTotalStats._meta_.fields["tips"].type = payments_BatchTotalType;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = BatchTotalStats;
}

