/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");

  /**
  * @constructor
  * @memberof payments
  */
  BatchTotalType = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof payments.BatchTotalType
    * @private
    */
    initialize: function() {
      this._class_ = BatchTotalType;
      this.count = undefined;
      this.total = undefined;
    },

    /**
    * Set the field value
    * Total count of types
    *
    * @memberof payments.BatchTotalType
    * @param {Number} count must be a long integer
    */
    setCount: function(count) {
      this.count = count;
    },

    /**
    * Get the field value
    * Total count of types
    * @memberof payments.BatchTotalType
    * @return {Number} must be a long integer
    */
    getCount: function() {
      return this.count;
    },

    /**
    * Set the field value
    * Total amount for type
    *
    * @memberof payments.BatchTotalType
    * @param {Number} total must be a long integer
    */
    setTotal: function(total) {
      this.total = total;
    },

    /**
    * Get the field value
    * Total amount for type
    * @memberof payments.BatchTotalType
    * @return {Number} must be a long integer
    */
    getTotal: function() {
      return this.total;
    },

    /**
    * @memberof payments.BatchTotalType
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

BatchTotalType._meta_ =  {fields:  {}};
BatchTotalType._meta_.fields["count"] = {};
BatchTotalType._meta_.fields["count"].type = Number;
BatchTotalType._meta_.fields["total"] = {};
BatchTotalType._meta_.fields["total"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = BatchTotalType;
}

