/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


CardTransactionState = {
  PENDING : "PENDING",
  CLOSED : "CLOSED"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CardTransactionState;
}

