/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");

  /**
  * @constructor
  */
  GiftCard = Class.create( {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function() {
      this._class_ = GiftCard;
      this.track2 = undefined;
      this.cardNumber = undefined;
      this.isManuallyEntered = false;
      this.deviceSerial = undefined;
    },

    /**
    * Set the field value
    * Track 2 Card Data
    *
    * @param {String} track2 
    */
    setTrack2: function(track2) {
      this.track2 = track2;
    },

    /**
    * Get the field value
    * Track 2 Card Data
      * @return {String} 
    */
    getTrack2: function() {
      return this.track2;
    },

    /**
    * Set the field value
    * Embossed Card Number
    *
    * @param {String} cardNumber 
    */
    setCardNumber: function(cardNumber) {
      this.cardNumber = cardNumber;
    },

    /**
    * Get the field value
    * Embossed Card Number
      * @return {String} 
    */
    getCardNumber: function() {
      return this.cardNumber;
    },

    /**
    * Set the field value
    * Was Account Number Manually Entered
    *
    * @param {Boolean} isManuallyEntered 
    */
    setIsManuallyEntered: function(isManuallyEntered) {
      this.isManuallyEntered = isManuallyEntered;
    },

    /**
    * Get the field value
    * Was Account Number Manually Entered
      * @return {Boolean} 
    */
    getIsManuallyEntered: function() {
      return this.isManuallyEntered;
    },

    /**
    * Set the field value
    * @param {String} deviceSerial 
    */
    setDeviceSerial: function(deviceSerial) {
      this.deviceSerial = deviceSerial;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getDeviceSerial: function() {
      return this.deviceSerial;
    },
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

GiftCard._meta_ =  {fields:  {}};
GiftCard._meta_.fields["track2"] = {};
GiftCard._meta_.fields["track2"].type = String;
GiftCard._meta_.fields["cardNumber"] = {};
GiftCard._meta_.fields["cardNumber"].type = String;
GiftCard._meta_.fields["isManuallyEntered"] = {};
GiftCard._meta_.fields["isManuallyEntered"].type = Boolean;
GiftCard._meta_.fields["deviceSerial"] = {};
GiftCard._meta_.fields["deviceSerial"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = GiftCard;
}

