/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


GiftCardState = {
  INVALID : "INVALID",
  ACTIVATED : "ACTIVATED",
  INACTIVE : "INACTIVE"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = GiftCardState;
}

