/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @memberof payments
* @enum {string}
*/
OverrideType = {
  RESELLER : "RESELLER",
  MERCHANT_GROUP : "MERCHANT_GROUP"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = OverrideType;
}

