/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var inventory_Item = require("../inventory/Item");
var inventory_Tag = require("../inventory/Tag");

  /**
  * @constructor
  * @memberof inventory
  */
  TagItem = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof inventory.TagItem
    * @private
    */
    initialize: function() {
      this._class_ = TagItem;
      this.tag = undefined;
      this.item = undefined;
    },

    /**
    * Set the field value
    * @memberof inventory.TagItem
    * @param {inventory.Tag} tag 
    */
    setTag: function(tag) {
      this.tag = tag;
    },

    /**
    * Get the field value
    * @memberof inventory.TagItem
    * @return {inventory.Tag} 
    */
    getTag: function() {
      return this.tag;
    },

    /**
    * Set the field value
    * @memberof inventory.TagItem
    * @param {inventory.Item} item 
    */
    setItem: function(item) {
      this.item = item;
    },

    /**
    * Get the field value
    * @memberof inventory.TagItem
    * @return {inventory.Item} 
    */
    getItem: function() {
      return this.item;
    },

    /**
    * @memberof inventory.TagItem
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

TagItem._meta_ =  {fields:  {}};
TagItem._meta_.fields["tag"] = {};
TagItem._meta_.fields["tag"].type = inventory_Tag;
TagItem._meta_.fields["item"] = {};
TagItem._meta_.fields["item"].type = inventory_Item;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = TagItem;
}

