/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var inventory_TaxRate = require("../inventory/TaxRate");
var inventory_Item = require("../inventory/Item");

  /**
  * @constructor
  */
  TaxRateItem = Class.create( {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function() {
      this._class_ = TaxRateItem;
      this.taxRate = undefined;
      this.item = undefined;
    },

    /**
    * Set the field value
    * @param {TaxRate} taxRate 
    */
    setTaxRate: function(taxRate) {
      this.taxRate = taxRate;
    },

    /**
    * Get the field value
    * @return {TaxRate} 
    */
    getTaxRate: function() {
      return this.taxRate;
    },

    /**
    * Set the field value
    * @param {Item} item 
    */
    setItem: function(item) {
      this.item = item;
    },

    /**
    * Get the field value
    * @return {Item} 
    */
    getItem: function() {
      return this.item;
    },
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

TaxRateItem._meta_ =  {fields:  {}};
TaxRateItem._meta_.fields["taxRate"] = {};
TaxRateItem._meta_.fields["taxRate"].type = inventory_TaxRate;
TaxRateItem._meta_.fields["item"] = {};
TaxRateItem._meta_.fields["item"].type = inventory_Item;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = TaxRateItem;
}

