/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  */
  AcknowledgementMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = AcknowledgementMessage;
      this.setMethod(remotemessage_Method["ACK"]);
      this.sourceMessageId = undefined;
    },

    /**
    * Set the field value
    * The remote message id that is being acknowledged
    *
    * @param {String} sourceMessageId 
    */
    setSourceMessageId: function(sourceMessageId) {
      this.sourceMessageId = sourceMessageId;
    },

    /**
    * Get the field value
    * The remote message id that is being acknowledged
      * @return {String} 
    */
    getSourceMessageId: function() {
      return this.sourceMessageId;
    }
  });

AcknowledgementMessage._meta_ =  {fields:  {}};
AcknowledgementMessage._meta_.fields["sourceMessageId"] = {};
AcknowledgementMessage._meta_.fields["sourceMessageId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = AcknowledgementMessage;
}

