/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  * @augments remotemessage.Message
  * @memberof remotemessage
  */
  CardDataRequestMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @memberof remotemessage.CardDataRequestMessage
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = CardDataRequestMessage;
      this.setMethod(remotemessage_Method["CARD_DATA"]);
      this.cardEntryMethods = undefined;
    },

    /**
    * Set the field value
    * Allowed entry methods
    *
    * @memberof remotemessage.CardDataRequestMessage
    * @param {Number} cardEntryMethods must be an integer
    */
    setCardEntryMethods: function(cardEntryMethods) {
      this.cardEntryMethods = cardEntryMethods;
    },

    /**
    * Get the field value
    * Allowed entry methods
    * @memberof remotemessage.CardDataRequestMessage
    * @return {Number} must be an integer
    */
    getCardEntryMethods: function() {
      return this.cardEntryMethods;
    }
  });

CardDataRequestMessage._meta_ =  {fields:  {}};
CardDataRequestMessage._meta_.fields["cardEntryMethods"] = {};
CardDataRequestMessage._meta_.fields["cardEntryMethods"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CardDataRequestMessage;
}

