/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  */
  CashbackSelectedMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = CashbackSelectedMessage;
      this.setMethod(remotemessage_Method["CASHBACK_SELECTED"]);
      this.cashbackAmount = undefined;
    },

    /**
    * Set the field value
    * Amount of cash selected
    *
    * @param {Number} cashbackAmount must be a long integer
    */
    setCashbackAmount: function(cashbackAmount) {
      this.cashbackAmount = cashbackAmount;
    },

    /**
    * Get the field value
    * Amount of cash selected
      * @return {Number} must be a long integer
    */
    getCashbackAmount: function() {
      return this.cashbackAmount;
    }
  });

CashbackSelectedMessage._meta_ =  {fields:  {}};
CashbackSelectedMessage._meta_.fields["cashbackAmount"] = {};
CashbackSelectedMessage._meta_.fields["cashbackAmount"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CashbackSelectedMessage;
}

