/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_ResultStatus = require("../remotemessage/ResultStatus");
var payments_Batch = require("../payments/Batch");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  */
  CloseoutResponseMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = CloseoutResponseMessage;
      this.setMethod(remotemessage_Method["CLOSEOUT_RESPONSE"]);
      this.reason = undefined;
      this.status = undefined;
      this.batch = undefined;
    },

    /**
    * Set the field value
    * Detail information.
    *
    * @param {String} reason 
    */
    setReason: function(reason) {
      this.reason = reason;
    },

    /**
    * Get the field value
    * Detail information.
      * @return {String} 
    */
    getReason: function() {
      return this.reason;
    },

    /**
    * Set the field value
    * The status of the request.
    *
    * @param {ResultStatus} status 
    */
    setStatus: function(status) {
      this.status = status;
    },

    /**
    * Get the field value
    * The status of the request.
      * @return {ResultStatus} 
    */
    getStatus: function() {
      return this.status;
    },

    /**
    * Set the field value
    * The closeout info.
    *
    * @param {Batch} batch 
    */
    setBatch: function(batch) {
      this.batch = batch;
    },

    /**
    * Get the field value
    * The closeout info.
      * @return {Batch} 
    */
    getBatch: function() {
      return this.batch;
    }
  });

CloseoutResponseMessage._meta_ =  {fields:  {}};
CloseoutResponseMessage._meta_.fields["reason"] = {};
CloseoutResponseMessage._meta_.fields["reason"].type = String;
CloseoutResponseMessage._meta_.fields["status"] = {};
CloseoutResponseMessage._meta_.fields["status"].type = remotemessage_ResultStatus;
CloseoutResponseMessage._meta_.fields["batch"] = {};
CloseoutResponseMessage._meta_.fields["batch"].type = payments_Batch;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CloseoutResponseMessage;
}

