/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  */
  DiscoveryRequestMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = DiscoveryRequestMessage;
      this.setMethod(remotemessage_Method["DISCOVERY_REQUEST"]);
      this.supportsOrderModification = undefined;
    },

    /**
    * Set the field value
    * If true then order modification operations are supportted.
    *
    * @param {Boolean|Null} supportsOrderModification 
    */
    setSupportsOrderModification: function(supportsOrderModification) {
      this.supportsOrderModification = supportsOrderModification;
    },

    /**
    * Get the field value
    * If true then order modification operations are supportted.
      * @return {Boolean|Null} 
    */
    getSupportsOrderModification: function() {
      return this.supportsOrderModification;
    }
  });

DiscoveryRequestMessage._meta_ =  {fields:  {}};
DiscoveryRequestMessage._meta_.fields["supportsOrderModification"] = {};
DiscoveryRequestMessage._meta_.fields["supportsOrderModification"].type = Boolean;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = DiscoveryRequestMessage;
}

