/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  */
  DiscoveryResponseMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = DiscoveryResponseMessage;
      this.setMethod(remotemessage_Method["DISCOVERY_RESPONSE"]);
      this.merchantId = undefined;
      this.merchantName = undefined;
      this.merchantMId = undefined;
      this.name = undefined;
      this.serial = undefined;
      this.model = undefined;
      this.ready = "false";
      this.supportsTipAdjust = "false";
      this.supportsManualRefund = "false";
      this.supportsMultiPayToken = "false";
    },

    /**
    * Set the field value
    * @param {String} merchantId 
    */
    setMerchantId: function(merchantId) {
      this.merchantId = merchantId;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getMerchantId: function() {
      return this.merchantId;
    },

    /**
    * Set the field value
    * @param {String} merchantName 
    */
    setMerchantName: function(merchantName) {
      this.merchantName = merchantName;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getMerchantName: function() {
      return this.merchantName;
    },

    /**
    * Set the field value
    * @param {String} merchantMId 
    */
    setMerchantMId: function(merchantMId) {
      this.merchantMId = merchantMId;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getMerchantMId: function() {
      return this.merchantMId;
    },

    /**
    * Set the field value
    * @param {String} name 
    */
    setName: function(name) {
      this.name = name;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getName: function() {
      return this.name;
    },

    /**
    * Set the field value
    * @param {String} serial 
    */
    setSerial: function(serial) {
      this.serial = serial;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getSerial: function() {
      return this.serial;
    },

    /**
    * Set the field value
    * @param {String} model 
    */
    setModel: function(model) {
      this.model = model;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getModel: function() {
      return this.model;
    },

    /**
    * Set the field value
    * @param {Boolean} ready 
    */
    setReady: function(ready) {
      this.ready = ready;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getReady: function() {
      return this.ready;
    },

    /**
    * Set the field value
    * @param {Boolean} supportsTipAdjust 
    */
    setSupportsTipAdjust: function(supportsTipAdjust) {
      this.supportsTipAdjust = supportsTipAdjust;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getSupportsTipAdjust: function() {
      return this.supportsTipAdjust;
    },

    /**
    * Set the field value
    * @param {Boolean} supportsManualRefund 
    */
    setSupportsManualRefund: function(supportsManualRefund) {
      this.supportsManualRefund = supportsManualRefund;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getSupportsManualRefund: function() {
      return this.supportsManualRefund;
    },

    /**
    * Set the field value
    * @param {Boolean} supportsMultiPayToken 
    */
    setSupportsMultiPayToken: function(supportsMultiPayToken) {
      this.supportsMultiPayToken = supportsMultiPayToken;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getSupportsMultiPayToken: function() {
      return this.supportsMultiPayToken;
    }
  });

DiscoveryResponseMessage._meta_ =  {fields:  {}};
DiscoveryResponseMessage._meta_.fields["merchantId"] = {};
DiscoveryResponseMessage._meta_.fields["merchantId"].type = String;
DiscoveryResponseMessage._meta_.fields["merchantName"] = {};
DiscoveryResponseMessage._meta_.fields["merchantName"].type = String;
DiscoveryResponseMessage._meta_.fields["merchantMId"] = {};
DiscoveryResponseMessage._meta_.fields["merchantMId"].type = String;
DiscoveryResponseMessage._meta_.fields["name"] = {};
DiscoveryResponseMessage._meta_.fields["name"].type = String;
DiscoveryResponseMessage._meta_.fields["serial"] = {};
DiscoveryResponseMessage._meta_.fields["serial"].type = String;
DiscoveryResponseMessage._meta_.fields["model"] = {};
DiscoveryResponseMessage._meta_.fields["model"].type = String;
DiscoveryResponseMessage._meta_.fields["ready"] = {};
DiscoveryResponseMessage._meta_.fields["ready"].type = Boolean;
DiscoveryResponseMessage._meta_.fields["supportsTipAdjust"] = {};
DiscoveryResponseMessage._meta_.fields["supportsTipAdjust"].type = Boolean;
DiscoveryResponseMessage._meta_.fields["supportsManualRefund"] = {};
DiscoveryResponseMessage._meta_.fields["supportsManualRefund"].type = Boolean;
DiscoveryResponseMessage._meta_.fields["supportsMultiPayToken"] = {};
DiscoveryResponseMessage._meta_.fields["supportsMultiPayToken"].type = Boolean;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = DiscoveryResponseMessage;
}

