/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_ErrorCode = require("../remotemessage/ErrorCode");

  /**
  * @constructor
  */
  ErrorCodeEnum = Class.create( {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function() {
      this._class_ = ErrorCodeEnum;
      this.errorCode = undefined;
    },

    /**
    * Set the field value
    * @param {ErrorCode} errorCode 
    */
    setErrorCode: function(errorCode) {
      this.errorCode = errorCode;
    },

    /**
    * Get the field value
    * @return {ErrorCode} 
    */
    getErrorCode: function() {
      return this.errorCode;
    },
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

ErrorCodeEnum._meta_ =  {fields:  {}};
ErrorCodeEnum._meta_.fields["errorCode"] = {};
ErrorCodeEnum._meta_.fields["errorCode"].type = remotemessage_ErrorCode;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = ErrorCodeEnum;
}

