/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var remotemessage_KeyPress = require("../remotemessage/KeyPress");

  /**
  * @constructor
  * @memberof remotemessage
  */
  InputOption = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof remotemessage.InputOption
    * @private
    */
    initialize: function() {
      this._class_ = InputOption;
      this.keyPress = undefined;
      this.description = undefined;
    },

    /**
    * Set the field value
    * The keypress this represents
    *
    * @memberof remotemessage.InputOption
    * @param {remotemessage.KeyPress} keyPress 
    */
    setKeyPress: function(keyPress) {
      this.keyPress = keyPress;
    },

    /**
    * Get the field value
    * The keypress this represents
    * @memberof remotemessage.InputOption
    * @return {remotemessage.KeyPress} 
    */
    getKeyPress: function() {
      return this.keyPress;
    },

    /**
    * Set the field value
    * A description of what this input option represents
    *
    * @memberof remotemessage.InputOption
    * @param {String} description 
    */
    setDescription: function(description) {
      this.description = description;
    },

    /**
    * Get the field value
    * A description of what this input option represents
    * @memberof remotemessage.InputOption
    * @return {String} 
    */
    getDescription: function() {
      return this.description;
    },

    /**
    * @memberof remotemessage.InputOption
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

InputOption._meta_ =  {fields:  {}};
InputOption._meta_.fields["keyPress"] = {};
InputOption._meta_.fields["keyPress"].type = remotemessage_KeyPress;
InputOption._meta_.fields["description"] = {};
InputOption._meta_.fields["description"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = InputOption;
}

