/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");
var remotemessage_AddLineItemAction = require("../remotemessage/AddLineItemAction");

  /**
  * @constructor
  * @augments remotemessage.Message
  * @memberof remotemessage
  */
  OrderActionAddLineItemMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @memberof remotemessage.OrderActionAddLineItemMessage
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = OrderActionAddLineItemMessage;
      this.setMethod(remotemessage_Method["ORDER_ACTION_ADD_LINE_ITEM"]);
      this.addLineItemAction = undefined;
    },

    /**
    * Set the field value
    * @memberof remotemessage.OrderActionAddLineItemMessage
    * @param {remotemessage.AddLineItemAction} addLineItemAction 
    */
    setAddLineItemAction: function(addLineItemAction) {
      this.addLineItemAction = addLineItemAction;
    },

    /**
    * Get the field value
    * @memberof remotemessage.OrderActionAddLineItemMessage
    * @return {remotemessage.AddLineItemAction} 
    */
    getAddLineItemAction: function() {
      return this.addLineItemAction;
    }
  });

OrderActionAddLineItemMessage._meta_ =  {fields:  {}};
OrderActionAddLineItemMessage._meta_.fields["addLineItemAction"] = {};
OrderActionAddLineItemMessage._meta_.fields["addLineItemAction"].type = remotemessage_AddLineItemAction;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = OrderActionAddLineItemMessage;
}

