/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");

  /**
  * @constructor
  * @memberof remotemessage
  */
  RemoveDiscountAction = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof remotemessage.RemoveDiscountAction
    * @private
    */
    initialize: function() {
      this._class_ = RemoveDiscountAction;
      this.discountId = undefined;
      this.lineItemId = undefined;
    },

    /**
    * Set the field value
    * @memberof remotemessage.RemoveDiscountAction
    * @param {String} discountId 
    */
    setDiscountId: function(discountId) {
      this.discountId = discountId;
    },

    /**
    * Get the field value
    * @memberof remotemessage.RemoveDiscountAction
    * @return {String} 
    */
    getDiscountId: function() {
      return this.discountId;
    },

    /**
    * Set the field value
    * @memberof remotemessage.RemoveDiscountAction
    * @param {String} lineItemId 
    */
    setLineItemId: function(lineItemId) {
      this.lineItemId = lineItemId;
    },

    /**
    * Get the field value
    * @memberof remotemessage.RemoveDiscountAction
    * @return {String} 
    */
    getLineItemId: function() {
      return this.lineItemId;
    },

    /**
    * @memberof remotemessage.RemoveDiscountAction
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

RemoveDiscountAction._meta_ =  {fields:  {}};
RemoveDiscountAction._meta_.fields["discountId"] = {};
RemoveDiscountAction._meta_.fields["discountId"].type = String;
RemoveDiscountAction._meta_.fields["lineItemId"] = {};
RemoveDiscountAction._meta_.fields["lineItemId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = RemoveDiscountAction;
}

