/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  * @augments remotemessage.Message
  * @memberof remotemessage
  */
  ThankYouMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @memberof remotemessage.ThankYouMessage
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = ThankYouMessage;
      this.setMethod(remotemessage_Method["SHOW_THANK_YOU_SCREEN"]);
    }
  });

ThankYouMessage._meta_ =  {fields:  {}};

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = ThankYouMessage;
}

