/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  */
  TipAdjustMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = TipAdjustMessage;
      this.setMethod(remotemessage_Method["TIP_ADJUST"]);
      this.tipAmount = undefined;
      this.orderId = undefined;
      this.paymentId = undefined;
    },

    /**
    * Set the field value
    * Amount paid in tips
    *
    * @param {Number} tipAmount must be a long integer
    */
    setTipAmount: function(tipAmount) {
      this.tipAmount = tipAmount;
    },

    /**
    * Get the field value
    * Amount paid in tips
      * @return {Number} must be a long integer
    */
    getTipAmount: function() {
      return this.tipAmount;
    },

    /**
    * Set the field value
    * Unique identifier for a order
    *
    * @param {String} orderId 
    */
    setOrderId: function(orderId) {
      this.orderId = orderId;
    },

    /**
    * Get the field value
    * Unique identifier for a order
      * @return {String} 
    */
    getOrderId: function() {
      return this.orderId;
    },

    /**
    * Set the field value
    * Unique identifier for a payment
    *
    * @param {String} paymentId 
    */
    setPaymentId: function(paymentId) {
      this.paymentId = paymentId;
    },

    /**
    * Get the field value
    * Unique identifier for a payment
      * @return {String} 
    */
    getPaymentId: function() {
      return this.paymentId;
    }
  });

TipAdjustMessage._meta_ =  {fields:  {}};
TipAdjustMessage._meta_.fields["tipAmount"] = {};
TipAdjustMessage._meta_.fields["tipAmount"].type = Number;
TipAdjustMessage._meta_.fields["orderId"] = {};
TipAdjustMessage._meta_.fields["orderId"].type = String;
TipAdjustMessage._meta_.fields["paymentId"] = {};
TipAdjustMessage._meta_.fields["paymentId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = TipAdjustMessage;
}

