/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


TransactionType = {
  PAYMENT : "PAYMENT",
  CREDIT : "CREDIT",
  AUTH : "AUTH",
  DATA : "DATA",
  BALANCE_INQUIRY : "BALANCE_INQUIRY"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = TransactionType;
}

