/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_TxState = require("../remotemessage/TxState");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  * @augments remotemessage.Message
  * @memberof remotemessage
  */
  TxStateMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @memberof remotemessage.TxStateMessage
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = TxStateMessage;
      this.setMethod(remotemessage_Method["TX_STATE"]);
      this.txState = undefined;
    },

    /**
    * Set the field value
    * Transaction state
    *
    * @memberof remotemessage.TxStateMessage
    * @param {remotemessage.TxState} txState 
    */
    setTxState: function(txState) {
      this.txState = txState;
    },

    /**
    * Get the field value
    * Transaction state
    * @memberof remotemessage.TxStateMessage
    * @return {remotemessage.TxState} 
    */
    getTxState: function() {
      return this.txState;
    }
  });

TxStateMessage._meta_ =  {fields:  {}};
TxStateMessage._meta_.fields["txState"] = {};
TxStateMessage._meta_.fields["txState"].type = remotemessage_TxState;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = TxStateMessage;
}

