/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @memberof remotemessage
* @enum {string}
*/
UiDirection = {
  ENTER : "ENTER",
  EXIT : "EXIT"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = UiDirection;
}

