/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

  /**
  * @constructor
  */
  VaultCardMessage = Class.create(remotemessage_Message, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = VaultCardMessage;
      this.setMethod(remotemessage_Method["VAULT_CARD"]);
      this.cardEntryMethods = undefined;
    },

    /**
    * Set the field value
    * Allowed entry methods
    *
    * @param {Number} cardEntryMethods must be an integer
    */
    setCardEntryMethods: function(cardEntryMethods) {
      this.cardEntryMethods = cardEntryMethods;
    },

    /**
    * Get the field value
    * Allowed entry methods
      * @return {Number} must be an integer
    */
    getCardEntryMethods: function() {
      return this.cardEntryMethods;
    }
  });

VaultCardMessage._meta_ =  {fields:  {}};
VaultCardMessage._meta_.fields["cardEntryMethods"] = {};
VaultCardMessage._meta_.fields["cardEntryMethods"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = VaultCardMessage;
}

