/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var employees_AccountRole = require("../employees/AccountRole");
var base_Reference = require("../base/Reference");

  /**
  * @constructor
  * @memberof employees
  */
  Role = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof employees.Role
    * @private
    */
    initialize: function() {
      this._class_ = Role;
      this.id = undefined;
      this.name = undefined;
      this.systemRole = undefined;
      this.employeesRef = undefined;
    },

    /**
    * Set the field value
    * Unique identifier
    *
    * @memberof employees.Role
    * @param {String} id 
    */
    setId: function(id) {
      this.id = id;
    },

    /**
    * Get the field value
    * Unique identifier
    * @memberof employees.Role
    * @return {String} 
    */
    getId: function() {
      return this.id;
    },

    /**
    * Set the field value
    * Full name of the role
    *
    * @memberof employees.Role
    * @param {String} name 
    */
    setName: function(name) {
      this.name = name;
    },

    /**
    * Get the field value
    * Full name of the role
    * @memberof employees.Role
    * @return {String} 
    */
    getName: function() {
      return this.name;
    },

    /**
    * Set the field value
    * Base System Role
    *
    * @memberof employees.Role
    * @param {employees.AccountRole} systemRole 
    */
    setSystemRole: function(systemRole) {
      this.systemRole = systemRole;
    },

    /**
    * Get the field value
    * Base System Role
    * @memberof employees.Role
    * @return {employees.AccountRole} 
    */
    getSystemRole: function() {
      return this.systemRole;
    },

    /**
    * Set the field value
    * employees with this role
    *
    * @memberof employees.Role
    * @param {Array.<base.Reference>} employeesRef An array of 
    */
    setEmployeesRef: function(employeesRef) {
      this.employeesRef = employeesRef;
    },

    /**
    * Get the field value
    * employees with this role
    * @memberof employees.Role
    * @return {Array.<base.Reference>} An array of 
    */
    getEmployeesRef: function() {
      return this.employeesRef;
    },

    /**
    * @memberof employees.Role
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

Role._meta_ =  {fields:  {}};
Role._meta_.fields["id"] = {};
Role._meta_.fields["id"].type = String;
Role._meta_.fields["name"] = {};
Role._meta_.fields["name"].type = String;
Role._meta_.fields["systemRole"] = {};
Role._meta_.fields["systemRole"].type = employees_AccountRole;
Role._meta_.fields["employeesRef"] = {};
Role._meta_.fields["employeesRef"].type = Array;
Role._meta_.fields["employeesRef"].elementType = base_Reference;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = Role;
}

