/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


BuildType = {
  ENG : "ENG",
  USER : "USER"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = BuildType;
}

