/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var device_BuildType = require("../device/BuildType");
var base_Reference = require("../base/Reference");

  /**
  * @constructor
  */
  Device = Class.create( {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function() {
      this._class_ = Device;
      this.id = undefined;
      this.name = undefined;
      this.model = undefined;
      this.merchant = undefined;
      this.orderPrefix = undefined;
      this.terminalPrefix = undefined;
      this.serial = undefined;
      this.buildNumber = undefined;
      this.secureId = undefined;
      this.buildType = undefined;
      this.cpuId = undefined;
      this.imei = undefined;
      this.imsi = undefined;
      this.simIccid = undefined;
      this.deviceCertificate = undefined;
      this.pedCertificate = undefined;
      this.deviceTypeName = undefined;
      this.pinDisabled = "false";
      this.offlinePayments = "false";
      this.offlinePaymentsAll = "false";
      this.offlinePaymentsLimit = undefined;
      this.offlinePaymentsPromptThreshold = undefined;
      this.secureReports = undefined;
      this.tipsEnabled = undefined;
      this.onPaperTipSignatures = undefined;
      this.autoPrint = undefined;
      this.hasDefaultEmployee = undefined;
      this.printOrderTime = undefined;
      this.skipReceiptScreen = undefined;
    },

    /**
    * Set the field value
    * Unique identifier
    *
    * @param {String} id 
    */
    setId: function(id) {
      this.id = id;
    },

    /**
    * Get the field value
    * Unique identifier
      * @return {String} 
    */
    getId: function() {
      return this.id;
    },

    /**
    * Set the field value
    * Name of the device (if entered)
    *
    * @param {String} name 
    */
    setName: function(name) {
      this.name = name;
    },

    /**
    * Get the field value
    * Name of the device (if entered)
      * @return {String} 
    */
    getName: function() {
      return this.name;
    },

    /**
    * Set the field value
    * @param {String} model 
    */
    setModel: function(model) {
      this.model = model;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getModel: function() {
      return this.model;
    },

    /**
    * Set the field value
    * @param {Reference} merchant 
    */
    setMerchant: function(merchant) {
      this.merchant = merchant;
    },

    /**
    * Get the field value
    * @return {Reference} 
    */
    getMerchant: function() {
      return this.merchant;
    },

    /**
    * Set the field value
    * @param {String} orderPrefix 
    */
    setOrderPrefix: function(orderPrefix) {
      this.orderPrefix = orderPrefix;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getOrderPrefix: function() {
      return this.orderPrefix;
    },

    /**
    * Set the field value
    * @param {Null|Number} terminalPrefix must be an integer
    */
    setTerminalPrefix: function(terminalPrefix) {
      this.terminalPrefix = terminalPrefix;
    },

    /**
    * Get the field value
    * @return {Null|Number} must be an integer
    */
    getTerminalPrefix: function() {
      return this.terminalPrefix;
    },

    /**
    * Set the field value
    * @param {String} serial 
    */
    setSerial: function(serial) {
      this.serial = serial;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getSerial: function() {
      return this.serial;
    },

    /**
    * Set the field value
    * @param {Number} buildNumber must be a long integer
    */
    setBuildNumber: function(buildNumber) {
      this.buildNumber = buildNumber;
    },

    /**
    * Get the field value
    * @return {Number} must be a long integer
    */
    getBuildNumber: function() {
      return this.buildNumber;
    },

    /**
    * Set the field value
    * @param {String} secureId 
    */
    setSecureId: function(secureId) {
      this.secureId = secureId;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getSecureId: function() {
      return this.secureId;
    },

    /**
    * Set the field value
    * @param {BuildType} buildType 
    */
    setBuildType: function(buildType) {
      this.buildType = buildType;
    },

    /**
    * Get the field value
    * @return {BuildType} 
    */
    getBuildType: function() {
      return this.buildType;
    },

    /**
    * Set the field value
    * @param {String} cpuId 
    */
    setCpuId: function(cpuId) {
      this.cpuId = cpuId;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getCpuId: function() {
      return this.cpuId;
    },

    /**
    * Set the field value
    * The IMEI of the device
    *
    * @param {String} imei 
    */
    setImei: function(imei) {
      this.imei = imei;
    },

    /**
    * Get the field value
    * The IMEI of the device
      * @return {String} 
    */
    getImei: function() {
      return this.imei;
    },

    /**
    * Set the field value
    * The IMSI of the SIM in the device (if present)
    *
    * @param {String} imsi 
    */
    setImsi: function(imsi) {
      this.imsi = imsi;
    },

    /**
    * Get the field value
    * The IMSI of the SIM in the device (if present)
      * @return {String} 
    */
    getImsi: function() {
      return this.imsi;
    },

    /**
    * Set the field value
    * The ICCID of the SIM in the device (if present)
    *
    * @param {String} simIccid 
    */
    setSimIccid: function(simIccid) {
      this.simIccid = simIccid;
    },

    /**
    * Get the field value
    * The ICCID of the SIM in the device (if present)
      * @return {String} 
    */
    getSimIccid: function() {
      return this.simIccid;
    },

    /**
    * Set the field value
    * @param {String} deviceCertificate 
    */
    setDeviceCertificate: function(deviceCertificate) {
      this.deviceCertificate = deviceCertificate;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getDeviceCertificate: function() {
      return this.deviceCertificate;
    },

    /**
    * Set the field value
    * @param {String} pedCertificate 
    */
    setPedCertificate: function(pedCertificate) {
      this.pedCertificate = pedCertificate;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getPedCertificate: function() {
      return this.pedCertificate;
    },

    /**
    * Set the field value
    * @param {String} deviceTypeName 
    */
    setDeviceTypeName: function(deviceTypeName) {
      this.deviceTypeName = deviceTypeName;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getDeviceTypeName: function() {
      return this.deviceTypeName;
    },

    /**
    * Set the field value
    * @param {Boolean} pinDisabled 
    */
    setPinDisabled: function(pinDisabled) {
      this.pinDisabled = pinDisabled;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getPinDisabled: function() {
      return this.pinDisabled;
    },

    /**
    * Set the field value
    * @param {Boolean} offlinePayments 
    */
    setOfflinePayments: function(offlinePayments) {
      this.offlinePayments = offlinePayments;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getOfflinePayments: function() {
      return this.offlinePayments;
    },

    /**
    * Set the field value
    * @param {Boolean} offlinePaymentsAll 
    */
    setOfflinePaymentsAll: function(offlinePaymentsAll) {
      this.offlinePaymentsAll = offlinePaymentsAll;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getOfflinePaymentsAll: function() {
      return this.offlinePaymentsAll;
    },

    /**
    * Set the field value
    * @param {Number} offlinePaymentsLimit must be a long integer
    */
    setOfflinePaymentsLimit: function(offlinePaymentsLimit) {
      this.offlinePaymentsLimit = offlinePaymentsLimit;
    },

    /**
    * Get the field value
    * @return {Number} must be a long integer
    */
    getOfflinePaymentsLimit: function() {
      return this.offlinePaymentsLimit;
    },

    /**
    * Set the field value
    * @param {Number} offlinePaymentsPromptThreshold must be a long integer
    */
    setOfflinePaymentsPromptThreshold: function(offlinePaymentsPromptThreshold) {
      this.offlinePaymentsPromptThreshold = offlinePaymentsPromptThreshold;
    },

    /**
    * Get the field value
    * @return {Number} must be a long integer
    */
    getOfflinePaymentsPromptThreshold: function() {
      return this.offlinePaymentsPromptThreshold;
    },

    /**
    * Set the field value
    * @param {Array.<Reference>} secureReports An array of 
    */
    setSecureReports: function(secureReports) {
      this.secureReports = secureReports;
    },

    /**
    * Get the field value
    * @return {Array.<Reference>} An array of 
    */
    getSecureReports: function() {
      return this.secureReports;
    },

    /**
    * Set the field value
    * @param {Boolean} tipsEnabled 
    */
    setTipsEnabled: function(tipsEnabled) {
      this.tipsEnabled = tipsEnabled;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getTipsEnabled: function() {
      return this.tipsEnabled;
    },

    /**
    * Set the field value
    * @param {Boolean} onPaperTipSignatures 
    */
    setOnPaperTipSignatures: function(onPaperTipSignatures) {
      this.onPaperTipSignatures = onPaperTipSignatures;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getOnPaperTipSignatures: function() {
      return this.onPaperTipSignatures;
    },

    /**
    * Set the field value
    * @param {Boolean} autoPrint 
    */
    setAutoPrint: function(autoPrint) {
      this.autoPrint = autoPrint;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getAutoPrint: function() {
      return this.autoPrint;
    },

    /**
    * Set the field value
    * @param {Boolean} hasDefaultEmployee 
    */
    setHasDefaultEmployee: function(hasDefaultEmployee) {
      this.hasDefaultEmployee = hasDefaultEmployee;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getHasDefaultEmployee: function() {
      return this.hasDefaultEmployee;
    },

    /**
    * Set the field value
    * @param {String} printOrderTime 
    */
    setPrintOrderTime: function(printOrderTime) {
      this.printOrderTime = printOrderTime;
    },

    /**
    * Get the field value
    * @return {String} 
    */
    getPrintOrderTime: function() {
      return this.printOrderTime;
    },

    /**
    * Set the field value
    * @param {Boolean} skipReceiptScreen 
    */
    setSkipReceiptScreen: function(skipReceiptScreen) {
      this.skipReceiptScreen = skipReceiptScreen;
    },

    /**
    * Get the field value
    * @return {Boolean} 
    */
    getSkipReceiptScreen: function() {
      return this.skipReceiptScreen;
    },
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

Device._meta_ =  {fields:  {}};
Device._meta_.fields["id"] = {};
Device._meta_.fields["id"].type = String;
Device._meta_.fields["name"] = {};
Device._meta_.fields["name"].type = String;
Device._meta_.fields["model"] = {};
Device._meta_.fields["model"].type = String;
Device._meta_.fields["merchant"] = {};
Device._meta_.fields["merchant"].type = base_Reference;
Device._meta_.fields["orderPrefix"] = {};
Device._meta_.fields["orderPrefix"].type = String;
Device._meta_.fields["terminalPrefix"] = {};
Device._meta_.fields["terminalPrefix"].type = Number;
Device._meta_.fields["serial"] = {};
Device._meta_.fields["serial"].type = String;
Device._meta_.fields["buildNumber"] = {};
Device._meta_.fields["buildNumber"].type = Number;
Device._meta_.fields["secureId"] = {};
Device._meta_.fields["secureId"].type = String;
Device._meta_.fields["buildType"] = {};
Device._meta_.fields["buildType"].type = device_BuildType;
Device._meta_.fields["cpuId"] = {};
Device._meta_.fields["cpuId"].type = String;
Device._meta_.fields["imei"] = {};
Device._meta_.fields["imei"].type = String;
Device._meta_.fields["imsi"] = {};
Device._meta_.fields["imsi"].type = String;
Device._meta_.fields["simIccid"] = {};
Device._meta_.fields["simIccid"].type = String;
Device._meta_.fields["deviceCertificate"] = {};
Device._meta_.fields["deviceCertificate"].type = String;
Device._meta_.fields["pedCertificate"] = {};
Device._meta_.fields["pedCertificate"].type = String;
Device._meta_.fields["deviceTypeName"] = {};
Device._meta_.fields["deviceTypeName"].type = String;
Device._meta_.fields["pinDisabled"] = {};
Device._meta_.fields["pinDisabled"].type = Boolean;
Device._meta_.fields["offlinePayments"] = {};
Device._meta_.fields["offlinePayments"].type = Boolean;
Device._meta_.fields["offlinePaymentsAll"] = {};
Device._meta_.fields["offlinePaymentsAll"].type = Boolean;
Device._meta_.fields["offlinePaymentsLimit"] = {};
Device._meta_.fields["offlinePaymentsLimit"].type = Number;
Device._meta_.fields["offlinePaymentsPromptThreshold"] = {};
Device._meta_.fields["offlinePaymentsPromptThreshold"].type = Number;
Device._meta_.fields["secureReports"] = {};
Device._meta_.fields["secureReports"].type = Array;
Device._meta_.fields["secureReports"].elementType = base_Reference;
Device._meta_.fields["tipsEnabled"] = {};
Device._meta_.fields["tipsEnabled"].type = Boolean;
Device._meta_.fields["onPaperTipSignatures"] = {};
Device._meta_.fields["onPaperTipSignatures"].type = Boolean;
Device._meta_.fields["autoPrint"] = {};
Device._meta_.fields["autoPrint"].type = Boolean;
Device._meta_.fields["hasDefaultEmployee"] = {};
Device._meta_.fields["hasDefaultEmployee"].type = Boolean;
Device._meta_.fields["printOrderTime"] = {};
Device._meta_.fields["printOrderTime"].type = String;
Device._meta_.fields["skipReceiptScreen"] = {};
Device._meta_.fields["skipReceiptScreen"].type = Boolean;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = Device;
}

