/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");

  /**
  * @constructor
  * @memberof base
  */
  CardData = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof base.CardData
    * @private
    */
    initialize: function() {
      this._class_ = CardData;
      this.track1 = undefined;
      this.track2 = undefined;
      this.track3 = undefined;
      this.encrypted = undefined;
      this.maskedTrack1 = undefined;
      this.maskedTrack2 = undefined;
      this.maskedTrack3 = undefined;
      this.pan = undefined;
      this.cardholderName = undefined;
      this.firstName = undefined;
      this.lastName = undefined;
      this.exp = undefined;
      this.last6 = undefined;
      this.first4 = undefined;
    },

    /**
    * Set the field value
    * The track1 data from the card.
    *
    * @memberof base.CardData
    * @param {String} track1 
    */
    setTrack1: function(track1) {
      this.track1 = track1;
    },

    /**
    * Get the field value
    * The track1 data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getTrack1: function() {
      return this.track1;
    },

    /**
    * Set the field value
    * The track2 data from the card.
    *
    * @memberof base.CardData
    * @param {String} track2 
    */
    setTrack2: function(track2) {
      this.track2 = track2;
    },

    /**
    * Get the field value
    * The track2 data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getTrack2: function() {
      return this.track2;
    },

    /**
    * Set the field value
    * The track3 data from the card.
    *
    * @memberof base.CardData
    * @param {String} track3 
    */
    setTrack3: function(track3) {
      this.track3 = track3;
    },

    /**
    * Get the field value
    * The track3 data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getTrack3: function() {
      return this.track3;
    },

    /**
    * Set the field value
    * Indicates if the data is encrypted.
    *
    * @memberof base.CardData
    * @param {Boolean} encrypted 
    */
    setEncrypted: function(encrypted) {
      this.encrypted = encrypted;
    },

    /**
    * Get the field value
    * Indicates if the data is encrypted.
    * @memberof base.CardData
    * @return {Boolean} 
    */
    getEncrypted: function() {
      return this.encrypted;
    },

    /**
    * Set the field value
    * The track1 data from the card.
    *
    * @memberof base.CardData
    * @param {String} maskedTrack1 
    */
    setMaskedTrack1: function(maskedTrack1) {
      this.maskedTrack1 = maskedTrack1;
    },

    /**
    * Get the field value
    * The track1 data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getMaskedTrack1: function() {
      return this.maskedTrack1;
    },

    /**
    * Set the field value
    * The track2 data from the card.
    *
    * @memberof base.CardData
    * @param {String} maskedTrack2 
    */
    setMaskedTrack2: function(maskedTrack2) {
      this.maskedTrack2 = maskedTrack2;
    },

    /**
    * Get the field value
    * The track2 data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getMaskedTrack2: function() {
      return this.maskedTrack2;
    },

    /**
    * Set the field value
    * The track3 data from the card.
    *
    * @memberof base.CardData
    * @param {String} maskedTrack3 
    */
    setMaskedTrack3: function(maskedTrack3) {
      this.maskedTrack3 = maskedTrack3;
    },

    /**
    * Get the field value
    * The track3 data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getMaskedTrack3: function() {
      return this.maskedTrack3;
    },

    /**
    * Set the field value
    * The pan data from the card.
    *
    * @memberof base.CardData
    * @param {String} pan 
    */
    setPan: function(pan) {
      this.pan = pan;
    },

    /**
    * Get the field value
    * The pan data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getPan: function() {
      return this.pan;
    },

    /**
    * Set the field value
    * The cardholderName data from the card.
    *
    * @memberof base.CardData
    * @param {String} cardholderName 
    */
    setCardholderName: function(cardholderName) {
      this.cardholderName = cardholderName;
    },

    /**
    * Get the field value
    * The cardholderName data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getCardholderName: function() {
      return this.cardholderName;
    },

    /**
    * Set the field value
    * The firstName data from the card.
    *
    * @memberof base.CardData
    * @param {String} firstName 
    */
    setFirstName: function(firstName) {
      this.firstName = firstName;
    },

    /**
    * Get the field value
    * The firstName data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getFirstName: function() {
      return this.firstName;
    },

    /**
    * Set the field value
    * The lastName data from the card.
    *
    * @memberof base.CardData
    * @param {String} lastName 
    */
    setLastName: function(lastName) {
      this.lastName = lastName;
    },

    /**
    * Get the field value
    * The lastName data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getLastName: function() {
      return this.lastName;
    },

    /**
    * Set the field value
    * The exp data from the card.
    *
    * @memberof base.CardData
    * @param {String} exp 
    */
    setExp: function(exp) {
      this.exp = exp;
    },

    /**
    * Get the field value
    * The exp data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getExp: function() {
      return this.exp;
    },

    /**
    * Set the field value
    * The last6 data from the card.
    *
    * @memberof base.CardData
    * @param {String} last6 
    */
    setLast6: function(last6) {
      this.last6 = last6;
    },

    /**
    * Get the field value
    * The last6 data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getLast6: function() {
      return this.last6;
    },

    /**
    * Set the field value
    * The first4 data from the card.
    *
    * @memberof base.CardData
    * @param {String} first4 
    */
    setFirst4: function(first4) {
      this.first4 = first4;
    },

    /**
    * Get the field value
    * The first4 data from the card.
    * @memberof base.CardData
    * @return {String} 
    */
    getFirst4: function() {
      return this.first4;
    },

    /**
    * @memberof base.CardData
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

CardData._meta_ =  {fields:  {}};
CardData._meta_.fields["track1"] = {};
CardData._meta_.fields["track1"].type = String;
CardData._meta_.fields["track2"] = {};
CardData._meta_.fields["track2"].type = String;
CardData._meta_.fields["track3"] = {};
CardData._meta_.fields["track3"].type = String;
CardData._meta_.fields["encrypted"] = {};
CardData._meta_.fields["encrypted"].type = Boolean;
CardData._meta_.fields["maskedTrack1"] = {};
CardData._meta_.fields["maskedTrack1"].type = String;
CardData._meta_.fields["maskedTrack2"] = {};
CardData._meta_.fields["maskedTrack2"].type = String;
CardData._meta_.fields["maskedTrack3"] = {};
CardData._meta_.fields["maskedTrack3"].type = String;
CardData._meta_.fields["pan"] = {};
CardData._meta_.fields["pan"].type = String;
CardData._meta_.fields["cardholderName"] = {};
CardData._meta_.fields["cardholderName"].type = String;
CardData._meta_.fields["firstName"] = {};
CardData._meta_.fields["firstName"].type = String;
CardData._meta_.fields["lastName"] = {};
CardData._meta_.fields["lastName"].type = String;
CardData._meta_.fields["exp"] = {};
CardData._meta_.fields["exp"].type = String;
CardData._meta_.fields["last6"] = {};
CardData._meta_.fields["last6"].type = String;
CardData._meta_.fields["first4"] = {};
CardData._meta_.fields["first4"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CardData;
}

