/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


ChallengeType = {
  DUPLICATE_CHALLENGE : "DUPLICATE_CHALLENGE",
  OFFLINE_CHALLENGE : "OFFLINE_CHALLENGE"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = ChallengeType;
}

