/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");

  /**
  * @constructor
  * @memberof base
  */
  Point = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof base.Point
    * @private
    */
    initialize: function() {
      this._class_ = Point;
      this.x = undefined;
      this.y = undefined;
    },

    /**
    * Set the field value
    * @memberof base.Point
    * @param {Number} x must be a long integer
    */
    setX: function(x) {
      this.x = x;
    },

    /**
    * Get the field value
    * @memberof base.Point
    * @return {Number} must be a long integer
    */
    getX: function() {
      return this.x;
    },

    /**
    * Set the field value
    * @memberof base.Point
    * @param {Number} y must be a long integer
    */
    setY: function(y) {
      this.y = y;
    },

    /**
    * Get the field value
    * @memberof base.Point
    * @return {Number} must be a long integer
    */
    getY: function() {
      return this.y;
    },

    /**
    * @memberof base.Point
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

Point._meta_ =  {fields:  {}};
Point._meta_.fields["x"] = {};
Point._meta_.fields["x"].type = Number;
Point._meta_.fields["y"] = {};
Point._meta_.fields["y"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = Point;
}

