/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotepay_TransactionType = require("../remotepay/TransactionType");
var remotepay_TransactionRequest = require("../remotepay/TransactionRequest");

/** A authorization request */
  /**
  * @constructor
  * @augments remotepay.TransactionRequest
  * @memberof remotepay
  */
  AuthRequest = Class.create(remotepay_TransactionRequest, {
    /**
    * Initialize the values for this.
    * @memberof remotepay.AuthRequest
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = AuthRequest;
      this.setType(remotepay_TransactionType["PAYMENT"]);
      this.disableCashback = undefined;
      this.taxAmount = undefined;
      this.allowOfflinePayment = undefined;
      this.approveOfflinePaymentWithoutPrompt = undefined;
    },

    /**
    * Set the field value
    * Do not allow cash back
    *
    * @memberof remotepay.AuthRequest
    * @param {Boolean|Null} disableCashback 
    */
    setDisableCashback: function(disableCashback) {
      this.disableCashback = disableCashback;
    },

    /**
    * Get the field value
    * Do not allow cash back
    * @memberof remotepay.AuthRequest
    * @return {Boolean|Null} 
    */
    getDisableCashback: function() {
      return this.disableCashback;
    },

    /**
    * Set the field value
    * Amount paid in tips
    *
    * @memberof remotepay.AuthRequest
    * @param {Number|Null} taxAmount must be a long integer, 
    */
    setTaxAmount: function(taxAmount) {
      this.taxAmount = taxAmount;
    },

    /**
    * Get the field value
    * Amount paid in tips
    * @memberof remotepay.AuthRequest
    * @return {Number|Null} must be a long integer, 
    */
    getTaxAmount: function() {
      return this.taxAmount;
    },

    /**
    * Set the field value
    * If true then offline payments can be accepted
    *
    * @memberof remotepay.AuthRequest
    * @param {Boolean|Null} allowOfflinePayment 
    */
    setAllowOfflinePayment: function(allowOfflinePayment) {
      this.allowOfflinePayment = allowOfflinePayment;
    },

    /**
    * Get the field value
    * If true then offline payments can be accepted
    * @memberof remotepay.AuthRequest
    * @return {Boolean|Null} 
    */
    getAllowOfflinePayment: function() {
      return this.allowOfflinePayment;
    },

    /**
    * Set the field value
    * If true then offline payments will be approved without a prompt.  Currently must be true.
    *
    * @memberof remotepay.AuthRequest
    * @param {Boolean|Null} approveOfflinePaymentWithoutPrompt 
    */
    setApproveOfflinePaymentWithoutPrompt: function(approveOfflinePaymentWithoutPrompt) {
      this.approveOfflinePaymentWithoutPrompt = approveOfflinePaymentWithoutPrompt;
    },

    /**
    * Get the field value
    * If true then offline payments will be approved without a prompt.  Currently must be true.
    * @memberof remotepay.AuthRequest
    * @return {Boolean|Null} 
    */
    getApproveOfflinePaymentWithoutPrompt: function() {
      return this.approveOfflinePaymentWithoutPrompt;
    }
  });

AuthRequest._meta_ =  {fields:  {}};
AuthRequest._meta_.fields["disableCashback"] = {};
AuthRequest._meta_.fields["disableCashback"].type = Boolean;
AuthRequest._meta_.fields["taxAmount"] = {};
AuthRequest._meta_.fields["taxAmount"].type = Number;
AuthRequest._meta_.fields["allowOfflinePayment"] = {};
AuthRequest._meta_.fields["allowOfflinePayment"].type = Boolean;
AuthRequest._meta_.fields["approveOfflinePaymentWithoutPrompt"] = {};
AuthRequest._meta_.fields["approveOfflinePaymentWithoutPrompt"].type = Boolean;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = AuthRequest;
}

