/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotepay_BaseRequest = require("../remotepay/BaseRequest");

/** Captures a previously made pre auth */
  /**
  * @constructor
  */
  CapturePreAuthRequest = Class.create(remotepay_BaseRequest, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = CapturePreAuthRequest;
      this.amount = undefined;
      this.tipAmount = undefined;
      this.paymentId = undefined;
    },

    /**
    * Set the field value
    * Total amount paid
    *
    * @param {Number} amount must be a long integer
    */
    setAmount: function(amount) {
      this.amount = amount;
    },

    /**
    * Get the field value
    * Total amount paid
      * @return {Number} must be a long integer
    */
    getAmount: function() {
      return this.amount;
    },

    /**
    * Set the field value
    * Amount paid in tips
    *
    * @param {Number|Null} tipAmount must be a long integer, 
    */
    setTipAmount: function(tipAmount) {
      this.tipAmount = tipAmount;
    },

    /**
    * Get the field value
    * Amount paid in tips
      * @return {Number|Null} must be a long integer, 
    */
    getTipAmount: function() {
      return this.tipAmount;
    },

    /**
    * Set the field value
    * Unique identifier for a payment
    *
    * @param {String} paymentId 
    */
    setPaymentId: function(paymentId) {
      this.paymentId = paymentId;
    },

    /**
    * Get the field value
    * Unique identifier for a payment
      * @return {String} 
    */
    getPaymentId: function() {
      return this.paymentId;
    }
  });

CapturePreAuthRequest._meta_ =  {fields:  {}};
CapturePreAuthRequest._meta_.fields["amount"] = {};
CapturePreAuthRequest._meta_.fields["amount"].type = Number;
CapturePreAuthRequest._meta_.fields["tipAmount"] = {};
CapturePreAuthRequest._meta_.fields["tipAmount"].type = Number;
CapturePreAuthRequest._meta_.fields["paymentId"] = {};
CapturePreAuthRequest._meta_.fields["paymentId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CapturePreAuthRequest;
}

