/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotepay_BaseRequest = require("../remotepay/BaseRequest");

/** Send a request for a closeout */
  /**
  * @constructor
  */
  CloseoutRequest = Class.create(remotepay_BaseRequest, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = CloseoutRequest;
      this.allowOpenTabs = "false";
      this.batchId = undefined;
    },

    /**
    * Set the field value
    * Allow closeout if there are open tabs
    *
    * @param {Boolean} allowOpenTabs 
    */
    setAllowOpenTabs: function(allowOpenTabs) {
      this.allowOpenTabs = allowOpenTabs;
    },

    /**
    * Get the field value
    * Allow closeout if there are open tabs
      * @return {Boolean} 
    */
    getAllowOpenTabs: function() {
      return this.allowOpenTabs;
    },

    /**
    * Set the field value
    * The batch id to close out.  If omitted, then the default current batch is used.
    *
    * @param {String} batchId 
    */
    setBatchId: function(batchId) {
      this.batchId = batchId;
    },

    /**
    * Get the field value
    * The batch id to close out.  If omitted, then the default current batch is used.
      * @return {String} 
    */
    getBatchId: function() {
      return this.batchId;
    }
  });

CloseoutRequest._meta_ =  {fields:  {}};
CloseoutRequest._meta_.fields["allowOpenTabs"] = {};
CloseoutRequest._meta_.fields["allowOpenTabs"].type = Boolean;
CloseoutRequest._meta_.fields["batchId"] = {};
CloseoutRequest._meta_.fields["batchId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CloseoutRequest;
}

