/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");

  /**
  * @constructor
  */
  Img = Class.create( {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function() {
      this._class_ = Img;
      this.src = undefined;
      this.width = undefined;
      this.height = undefined;
    },

    /**
    * Set the field value
    * The url to the image if available
    *
    * @param {String} src 
    */
    setSrc: function(src) {
      this.src = src;
    },

    /**
    * Get the field value
    * The url to the image if available
      * @return {String} 
    */
    getSrc: function() {
      return this.src;
    },

    /**
    * Set the field value
    * The width of the image if available
    *
    * @param {Number} width must be a long integer
    */
    setWidth: function(width) {
      this.width = width;
    },

    /**
    * Get the field value
    * The width of the image if available
      * @return {Number} must be a long integer
    */
    getWidth: function() {
      return this.width;
    },

    /**
    * Set the field value
    * The height of the image if available
    *
    * @param {Number} height must be a long integer
    */
    setHeight: function(height) {
      this.height = height;
    },

    /**
    * Get the field value
    * The height of the image if available
      * @return {Number} must be a long integer
    */
    getHeight: function() {
      return this.height;
    },
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

Img._meta_ =  {fields:  {}};
Img._meta_.fields["src"] = {};
Img._meta_.fields["src"].type = String;
Img._meta_.fields["width"] = {};
Img._meta_.fields["width"].type = Number;
Img._meta_.fields["height"] = {};
Img._meta_.fields["height"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = Img;
}

