/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotepay_KeyPress = require("../remotepay/KeyPress");

  /**
  * @constructor
  * @memberof remotepay
  */
  KeyPressEnum = Class.create( {
    /**
    * Initialize the values for this.
    * @memberof remotepay.KeyPressEnum
    * @private
    */
    initialize: function() {
      this._class_ = KeyPressEnum;
      this.status = undefined;
    },

    /**
    * Set the field value
    * @memberof remotepay.KeyPressEnum
    * @param {remotepay.KeyPress} status 
    */
    setStatus: function(status) {
      this.status = status;
    },

    /**
    * Get the field value
    * @memberof remotepay.KeyPressEnum
    * @return {remotepay.KeyPress} 
    */
    getStatus: function() {
      return this.status;
    },

    /**
    * @memberof remotepay.KeyPressEnum
    * @private
    */
    getMetaInfo: function(fieldName) {
      var curclass = this._class_;
      do {
        var fieldMetaInfo = curclass._meta_.fields[fieldName];
        if(fieldMetaInfo) {
          return fieldMetaInfo;
        }
        curclass = curclass.superclass;
      } while(curclass);
      return null;
    },

    toString: function() {
      return JSON.stringify(this);
    }

  });

KeyPressEnum._meta_ =  {fields:  {}};
KeyPressEnum._meta_.fields["status"] = {};
KeyPressEnum._meta_.fields["status"].type = remotepay_KeyPress;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = KeyPressEnum;
}

