/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotepay_TransactionType = require("../remotepay/TransactionType");
var remotepay_TransactionRequest = require("../remotepay/TransactionRequest");

  /**
  * @constructor
  */
  PreAuthRequest = Class.create(remotepay_TransactionRequest, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = PreAuthRequest;
      this.setType(remotepay_TransactionType["AUTH"]);
    }
  });

PreAuthRequest._meta_ =  {fields:  {}};

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = PreAuthRequest;
}

