/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var remotepay_BaseRequest = require("../remotepay/BaseRequest");

  /**
  * @constructor
  * @augments remotepay.BaseRequest
  * @memberof remotepay
  */
  ReadCardDataRequest = Class.create(remotepay_BaseRequest, {
    /**
    * Initialize the values for this.
    * @memberof remotepay.ReadCardDataRequest
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = ReadCardDataRequest;
      this.isForceSwipePinEntry = undefined;
      this.cardEntryMethods = undefined;
    },

    /**
    * Set the field value
    * If true, then if the card is swiped, a pin entry must be done.
    *
    * @memberof remotepay.ReadCardDataRequest
    * @param {Boolean} isForceSwipePinEntry 
    */
    setIsForceSwipePinEntry: function(isForceSwipePinEntry) {
      this.isForceSwipePinEntry = isForceSwipePinEntry;
    },

    /**
    * Get the field value
    * If true, then if the card is swiped, a pin entry must be done.
    * @memberof remotepay.ReadCardDataRequest
    * @return {Boolean} 
    */
    getIsForceSwipePinEntry: function() {
      return this.isForceSwipePinEntry;
    },

    /**
    * Set the field value
    * The bit mask of allowable card read types.
    *
    * @memberof remotepay.ReadCardDataRequest
    * @param {Number} cardEntryMethods must be an integer
    */
    setCardEntryMethods: function(cardEntryMethods) {
      this.cardEntryMethods = cardEntryMethods;
    },

    /**
    * Get the field value
    * The bit mask of allowable card read types.
    * @memberof remotepay.ReadCardDataRequest
    * @return {Number} must be an integer
    */
    getCardEntryMethods: function() {
      return this.cardEntryMethods;
    }
  });

ReadCardDataRequest._meta_ =  {fields:  {}};
ReadCardDataRequest._meta_.fields["isForceSwipePinEntry"] = {};
ReadCardDataRequest._meta_.fields["isForceSwipePinEntry"].type = Boolean;
ReadCardDataRequest._meta_.fields["cardEntryMethods"] = {};
ReadCardDataRequest._meta_.fields["cardEntryMethods"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = ReadCardDataRequest;
}

