/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotepay_BaseResponse = require("../remotepay/BaseResponse");
var payments_Refund = require("../payments/Refund");

  /**
  * @constructor
  */
  RefundPaymentResponse = Class.create(remotepay_BaseResponse, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = RefundPaymentResponse;
      this.refund = undefined;
    },

    /**
    * Set the field value
    * The actual refund from the request
    *
    * @param {Refund} refund 
    */
    setRefund: function(refund) {
      this.refund = refund;
    },

    /**
    * Get the field value
    * The actual refund from the request
      * @return {Refund} 
    */
    getRefund: function() {
      return this.refund;
    }
  });

RefundPaymentResponse._meta_ =  {fields:  {}};
RefundPaymentResponse._meta_.fields["refund"] = {};
RefundPaymentResponse._meta_.fields["refund"].type = payments_Refund;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = RefundPaymentResponse;
}

