/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


ResponseCode = {
  SUCCESS : "SUCCESS",
  FAIL : "FAIL",
  UNSUPPORTED : "UNSUPPORTED",
  CANCEL : "CANCEL",
  ERROR : "ERROR"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = ResponseCode;
}

