/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var remotepay_BaseRequest = require("../remotepay/BaseRequest");
var payments_Payment = require("../payments/Payment");
var base_Signature = require("../base/Signature");

  /**
  * @constructor
  * @augments remotepay.BaseRequest
  * @memberof remotepay
  */
  VerifySignatureRequest = Class.create(remotepay_BaseRequest, {
    /**
    * Initialize the values for this.
    * @memberof remotepay.VerifySignatureRequest
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = VerifySignatureRequest;
      this.payment = undefined;
      this.signature = undefined;
    },

    /**
    * Set the field value
    * Payment that the signature is verifying for
    *
    * @memberof remotepay.VerifySignatureRequest
    * @param {payments.Payment} payment 
    */
    setPayment: function(payment) {
      this.payment = payment;
    },

    /**
    * Get the field value
    * Payment that the signature is verifying for
    * @memberof remotepay.VerifySignatureRequest
    * @return {payments.Payment} 
    */
    getPayment: function() {
      return this.payment;
    },

    /**
    * Set the field value
    * @memberof remotepay.VerifySignatureRequest
    * @param {base.Signature} signature 
    */
    setSignature: function(signature) {
      this.signature = signature;
    },

    /**
    * Get the field value
    * @memberof remotepay.VerifySignatureRequest
    * @return {base.Signature} 
    */
    getSignature: function() {
      return this.signature;
    }
  });

VerifySignatureRequest._meta_ =  {fields:  {}};
VerifySignatureRequest._meta_.fields["payment"] = {};
VerifySignatureRequest._meta_.fields["payment"].type = payments_Payment;
VerifySignatureRequest._meta_.fields["signature"] = {};
VerifySignatureRequest._meta_.fields["signature"].type = base_Signature;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = VerifySignatureRequest;
}

