/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

// Prototype.js required
require("prototype");
var remotepay_BaseRequest = require("../remotepay/BaseRequest");
var payments_Payment = require("../payments/Payment");
var base_Signature = require("../base/Signature");

  /**
  * @constructor
  */
  VerifySignatureRequest = Class.create(remotepay_BaseRequest, {
    /**
    * Initialize the values for this.
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = VerifySignatureRequest;
      this.payment = undefined;
      this.signature = undefined;
    },

    /**
    * Set the field value
    * Payment that the signature is verifying for
    *
    * @param {Payment} payment 
    */
    setPayment: function(payment) {
      this.payment = payment;
    },

    /**
    * Get the field value
    * Payment that the signature is verifying for
      * @return {Payment} 
    */
    getPayment: function() {
      return this.payment;
    },

    /**
    * Set the field value
    * @param {Signature} signature 
    */
    setSignature: function(signature) {
      this.signature = signature;
    },

    /**
    * Get the field value
    * @return {Signature} 
    */
    getSignature: function() {
      return this.signature;
    }
  });

VerifySignatureRequest._meta_ =  {fields:  {}};
VerifySignatureRequest._meta_.fields["payment"] = {};
VerifySignatureRequest._meta_.fields["payment"].type = payments_Payment;
VerifySignatureRequest._meta_.fields["signature"] = {};
VerifySignatureRequest._meta_.fields["signature"].type = base_Signature;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = VerifySignatureRequest;
}

