/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var Class = require("../Class.js");
var remotepay_BaseResponse = require("../remotepay/BaseResponse");

  /**
  * @constructor
  * @augments remotepay.BaseResponse
  * @memberof remotepay
  */
  VoidPaymentResponse = Class.create(remotepay_BaseResponse, {
    /**
    * Initialize the values for this.
    * @memberof remotepay.VoidPaymentResponse
    * @private
    */
    initialize: function($super) {
      $super();
      this._class_ = VoidPaymentResponse;
      this.paymentId = undefined;
    },

    /**
    * Set the field value
    * The id of the payment voided
    *
    * @memberof remotepay.VoidPaymentResponse
    * @param {String} paymentId 
    */
    setPaymentId: function(paymentId) {
      this.paymentId = paymentId;
    },

    /**
    * Get the field value
    * The id of the payment voided
    * @memberof remotepay.VoidPaymentResponse
    * @return {String} 
    */
    getPaymentId: function() {
      return this.paymentId;
    }
  });

VoidPaymentResponse._meta_ =  {fields:  {}};
VoidPaymentResponse._meta_.fields["paymentId"] = {};
VoidPaymentResponse._meta_.fields["paymentId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = VoidPaymentResponse;
}

